#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# ---------------------------------------#
# VARIABLES                              #
#----------------------------------------#
terminal=kitty
menu=wofi
mod=Super

# ---------------------------------------#
# INPUT CONFIGURATION                    #
# ---------------------------------------#
riverctl input pointer-1267-12739-ELAN050B:00_04F3:31C3_Touchpad events enabled
# riverctl input pointer-1267-12739-ELAN050B:00_04F3:31C3_Touchpad natural-scroll enabled
riverctl input pointer-1267-12739-ELAN050B:00_04F3:31C3_Touchpad tap enabled
riverctl input pointer-1267-12739-ELAN050B:00_04F3:31C3_Touchpad accel-profile flat

# ---------------------------------------#
# Keybindings                            #
# ---------------------------------------#
riverctl map normal $mod Return spawn $terminal
riverctl map normal $mod D spawn $menu

# Super+Q to close the focused view
riverctl map normal $mod+Shift Q close

# Super+Shift+E to exit river
riverctl map normal $mod+Shift E exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal $mod Period focus-output next
riverctl map normal $mod Comma focus-output previous

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Period send-to-output next
riverctl map normal $mod+Shift Comma send-to-output previous

# Super+Shift+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod+Shift Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
riverctl map normal $mod H send-layout-cmd rivercarro "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivercarro "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
riverctl map normal $mod+Shift H send-layout-cmd rivercarro "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivercarro "main-count -1"

# Super+Alt+{H,J,K,L} to move views
riverctl map normal $mod+Alt H move left 100
riverctl map normal $mod+Alt J move down 100
riverctl map normal $mod+Alt K move up 100
riverctl map normal $mod+Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+Alt+Control H snap left
riverctl map normal $mod+Alt+Control J snap down
riverctl map normal $mod+Alt+Control K snap up
riverctl map normal $mod+Alt+Control L snap right

# Super+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal $mod+Alt+Shift H resize horizontal -100
riverctl map normal $mod+Alt+Shift J resize vertical 100
riverctl map normal $mod+Alt+Shift K resize vertical -100
riverctl map normal $mod+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Super $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Super+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super+Control $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift+Control $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Super+Space to toggle float
riverctl map normal $mod Space toggle-float

# Super+F to toggle fullscreen
riverctl map normal $mod F toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up    send-layout-cmd rivercarro "main-location top"
riverctl map normal $mod Right send-layout-cmd rivercarro "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivercarro "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivercarro "main-location left"

# monocle
riverctl map normal $mod M     send-layout-cmd rivercarro "main-location monocle"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # MPC Controls
    riverctl map $mode Super XF86AudioMute         spawn 'mpc toggle'
    riverctl map $mode Super XF86AudioLowerVolume  spawn 'mpc prev'
    riverctl map $mode Super XF86AudioRaiseVolume  spawn 'mpc next'

    # Pulseaudio Controls
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ +5%'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ -5%'
    riverctl map $mode None XF86AudioMute         spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'
    riverctl map $mode None XF86AudioMicMute      spawn 'pactl set-source-mute @DEFAULT_SOURCE@ toggle'

    riverctl map $mode Shift XF86AudioMute         spawn 'pactl set-source-mute @DEFAULT_SOURCE@ toggle'
    riverctl map $mode Shift XF86AudioRaiseVolume  spawn 'pactl set-source-volume @DEFAULT_SOURCE@ +5%'
    riverctl map $mode Shift XF86AudioLowerVolume  spawn 'pactl set-source-volume @DEFAULT_SOURCE@ -5%'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Brightness Control
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set +5%'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'

    riverctl map $mode None Print spawn 'IMG=~/Pictures/$(date +"%s_grim.png") && grim $IMG && wl-copy < $IMG'
    riverctl map $mode Shift Print spawn 'IMG=~/Pictures/$(date +"%s_grim.png") && grim -g "$(slurp)" $IMG && wl-copy < $IMG'
done

# Set background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x93a1a1
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 50 300

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivercarro

exec brightnessctl s 30% &
exec waybar &
exec gentoo-pipewire-launcher &
exec mpd &
exec dunst &
exec swaybg -m fill -i ~/Pictures/cyberpunk.jpg &
exec swayidle -w \
         timeout 1800 'swaylock -f -c 000000' \
         timeout 1800 'swaymsg "output * dpms off"' resume 'swaymsg "output * dpms on"' \
         before-sleep 'swaylock -f -c 000000' &
# exec rivertile -view-padding 5 -outer-padding 5 -main-ratio 0.5
exec rivercarro -no-smart-gaps -main-ratio 0.5
